version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: monday
    time: "15:22"
    timezone: "America/Buenos_Aires"
  allow:
    - dependency-name: "@dcl/*"
    - dependency-name: "@catalyst/*"
    - dependency-name: "@well-known-components/*"
    - dependency-name: "dcl-*"
  versioning-strategy: auto
  commit-message:
      prefix: "chore: "

